service: #### PLACEHOLDER ####
frameworkVersion: "3"
useDotenv: true
package:
  individually: true

provider:
  name: aws
  profile: ${env:AWS_PROFILE}
  region: ${env:AWS_REGION}
  stage: ${opt:stage, "dev"}
  runtime: provided.al2
  architecture: arm64
  timeout: 5
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "lambda:InvokeFunction"
          Resource: "*"

functions:
  api:
    handler: bootstrap
    package:
      individually: true
      artifact: api/lambda.zip
    events:
      - httpApi: "*"
